Initial working version
getPubKey.py - is a flask app that fetches public key given
the wallet address
The rest is a vite project that provides a simple web interface
to fetch the pubkeys for multiple wallets

Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
error: could not apply 6775f56... Initial working version
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 6775f56... Initial working version#	new file:   node_modules/eslint/lib/rules/implicit-arrow-linebreak.js